config/routes.rb
Dailydeals::Application.routes.draw do

  resources :payment_methods

  resources :coupons

  resources :locations
  
  resources :businesses

  resources :sales

  resources :deals do
    collection do
      get 'current'
    end
  end
  
  devise_for :users do
    get "/users/login" => "devise/sessions#new"
    get "/users/logout" => "devise/sessions#destroy"
  end

  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
  end
  
  match "/contact",     :to => "pages#contact",                    :as => :contact
  match "/howitworks",  :to => "pages#show", :id => "howitworks",  :as => :howitworks
  match "/faq",         :to => "pages#show", :id => "faq",         :as => :faq
  match "/termsofsale", :to => "pages#show", :id => "termsofsale", :as => :termsofsale
  match "/termsofuse",  :to => "pages#show", :id => "termsofuse",  :as => :termsofuse
  match "/privacy",     :to => "pages#show", :id => "privacy",     :as => :privacy
  
  root :to => "deals#current"

end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  # GET /businesses
  # GET /businesses.xml
  def index
    @businesses = Business.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @businesses }
    end
  end

  # GET /businesses/1
  # GET /businesses/1.xml
  def show
    @business = Business.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @business }
    end
  end

  # GET /businesses/new
  # GET /businesses/new.xml
  def new
    @business = Business.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @business }
    end
  end

  # GET /businesses/1/edit
  def edit
    @business = Business.find(params[:id])
  end

  # POST /businesses
  # POST /businesses.xml
  def create
    @business = Business.new(params[:business])

    respond_to do |format|
      if @business.save
        format.html { redirect_to(@business, :notice => 'Business was successfully created.') }
        format.xml  { render :xml => @business, :status => :created, :location => @business }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @business.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /businesses/1
  # PUT /businesses/1.xml
  def update
    @business = Business.find(params[:id])

    respond_to do |format|
      if @business.update_attributes(params[:business])
        format.html { redirect_to(@business, :notice => 'Business was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @business.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /businesses/1
  # DELETE /businesses/1.xml
  def destroy
    @business = Business.find(params[:id])
    @business.destroy

    respond_to do |format|
      format.html { redirect_to(businesses_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/views/businesses/_form.html.erb
<%= form_for(@business) do |f| %>
  <% if @business.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@business.errors.count, "error") %> prohibited this business from being saved:</h2>

      <ul>
      <% @business.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address_1 %><br />
    <%= f.text_field :address_1 %>
  </div>
  <div class="field">
    <%= f.label :address_2 %><br />
    <%= f.text_field :address_2 %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br />
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :info %><br />
    <%= f.text_area :info %>
  </div>
  <div class="field">
    <%= f.label :venue_id %><br />
    <%= f.text_field :venue_id %>
  </div>
  <div class="field">
    <%= f.label :charity_photo %><br />
    <%= f.text_field :charity_photo %>
  </div>
  <div class="field">
    <%= f.label :charity_text %><br />
    <%= f.text_area :charity_text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/businesses/edit.html.erb
<h1>Editing business</h1>

<%= render 'form' %>

<%= link_to 'Show', @business %> |
<%= link_to 'Back', businesses_path %>

app/views/businesses/index.html.erb
<h1>Listing businesses</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Address 1</th>
    <th>Address 2</th>
    <th>City</th>
    <th>State</th>
    <th>Zip</th>
    <th>Url</th>
    <th>Info</th>
    <th>Venue</th>
    <th>Charity photo</th>
    <th>Charity text</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @businesses.each do |business| %>
  <tr>
    <td><%= business.name %></td>
    <td><%= business.address_1 %></td>
    <td><%= business.address_2 %></td>
    <td><%= business.city %></td>
    <td><%= business.state %></td>
    <td><%= business.zip %></td>
    <td><%= business.url %></td>
    <td><%= business.info %></td>
    <td><%= business.venue_id %></td>
    <td><%= business.charity_photo %></td>
    <td><%= business.charity_text %></td>
    <td><%= link_to 'Show', business %></td>
    <td><%= link_to 'Edit', edit_business_path(business) %></td>
    <td><%= link_to 'Destroy', business, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Business', new_business_path %>

app/views/businesses/new.html.erb
<h1>New business</h1>

<%= render 'form' %>

<%= link_to 'Back', businesses_path %>

app/views/businesses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @business.name %>
</p>

<p>
  <b>Address 1:</b>
  <%= @business.address_1 %>
</p>

<p>
  <b>Address 2:</b>
  <%= @business.address_2 %>
</p>

<p>
  <b>City:</b>
  <%= @business.city %>
</p>

<p>
  <b>State:</b>
  <%= @business.state %>
</p>

<p>
  <b>Zip:</b>
  <%= @business.zip %>
</p>

<p>
  <b>Url:</b>
  <%= @business.url %>
</p>

<p>
  <b>Info:</b>
  <%= @business.info %>
</p>

<p>
  <b>Venue:</b>
  <%= @business.venue_id %>
</p>

<p>
  <b>Charity photo:</b>
  <%= @business.charity_photo %>
</p>

<p>
  <b>Charity text:</b>
  <%= @business.charity_text %>
</p>


<%= link_to 'Edit', edit_business_path(@business) %> |
<%= link_to 'Back', businesses_path %>