config/routes.rb
Dailydeals::Application.routes.draw do

  resources :payment_methods

  resources :coupons

  resources :locations
  
  resources :businesses

  resources :sales

  resources :deals do
    collection do
      get 'current'
    end
  end
  
  devise_for :users do
    get "/users/login" => "devise/sessions#new"
    get "/users/logout" => "devise/sessions#destroy"
  end

  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
  end
  
  match "/contact",     :to => "pages#contact",                    :as => :contact
  match "/howitworks",  :to => "pages#show", :id => "howitworks",  :as => :howitworks
  match "/faq",         :to => "pages#show", :id => "faq",         :as => :faq
  match "/termsofsale", :to => "pages#show", :id => "termsofsale", :as => :termsofsale
  match "/termsofuse",  :to => "pages#show", :id => "termsofuse",  :as => :termsofuse
  match "/privacy",     :to => "pages#show", :id => "privacy",     :as => :privacy
  
  root :to => "deals#current"

end

app/models/payment_method.rb
class PaymentMethod < ActiveRecord::Base
  has_one :user
end

app/controllers/payment_methods_controller.rb
class PaymentMethodsController < ApplicationController
  # GET /payment_methods
  # GET /payment_methods.xml
  def index
    @payment_methods = PaymentMethod.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @payment_methods }
    end
  end

  # GET /payment_methods/1
  # GET /payment_methods/1.xml
  def show
    @payment_method = PaymentMethod.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @payment_method }
    end
  end

  # GET /payment_methods/new
  # GET /payment_methods/new.xml
  def new
    @payment_method = PaymentMethod.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @payment_method }
    end
  end

  # GET /payment_methods/1/edit
  def edit
    @payment_method = PaymentMethod.find(params[:id])
  end

  # POST /payment_methods
  # POST /payment_methods.xml
  def create
    @payment_method = PaymentMethod.new(params[:payment_method])

    respond_to do |format|
      if @payment_method.save
        format.html { redirect_to(@payment_method, :notice => 'Payment method was successfully created.') }
        format.xml  { render :xml => @payment_method, :status => :created, :location => @payment_method }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @payment_method.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /payment_methods/1
  # PUT /payment_methods/1.xml
  def update
    @payment_method = PaymentMethod.find(params[:id])

    respond_to do |format|
      if @payment_method.update_attributes(params[:payment_method])
        format.html { redirect_to(@payment_method, :notice => 'Payment method was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @payment_method.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /payment_methods/1
  # DELETE /payment_methods/1.xml
  def destroy
    @payment_method = PaymentMethod.find(params[:id])
    @payment_method.destroy

    respond_to do |format|
      format.html { redirect_to(payment_methods_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/payment_methods_helper.rb
module PaymentMethodsHelper
end

app/views/payment_methods/_form.html.erb
<%= form_for(@payment_method) do |f| %>
  <% if @payment_method.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment_method.errors.count, "error") %> prohibited this payment_method from being saved:</h2>

      <ul>
      <% @payment_method.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cs_subscription_id %><br />
    <%= f.text_field :cs_subscription_id %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :address_1 %><br />
    <%= f.text_field :address_1 %>
  </div>
  <div class="field">
    <%= f.label :address_2 %><br />
    <%= f.text_field :address_2 %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br />
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :cc_last_4 %><br />
    <%= f.text_field :cc_last_4 %>
  </div>
  <div class="field">
    <%= f.label :cc_type %><br />
    <%= f.text_field :cc_type %>
  </div>
  <div class="field">
    <%= f.label :cc_exp_month %><br />
    <%= f.text_field :cc_exp_month %>
  </div>
  <div class="field">
    <%= f.label :cc_exp_year %><br />
    <%= f.text_field :cc_exp_year %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/payment_methods/edit.html.erb
<h1>Editing payment_method</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment_method %> |
<%= link_to 'Back', payment_methods_path %>

app/views/payment_methods/index.html.erb
<h1>Listing payment_methods</h1>

<table>
  <tr>
    <th>Cs subscription</th>
    <th>First name</th>
    <th>Last name</th>
    <th>Address 1</th>
    <th>Address 2</th>
    <th>City</th>
    <th>State</th>
    <th>Zip</th>
    <th>Cc last 4</th>
    <th>Cc type</th>
    <th>Cc exp month</th>
    <th>Cc exp year</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @payment_methods.each do |payment_method| %>
  <tr>
    <td><%= payment_method.cs_subscription_id %></td>
    <td><%= payment_method.first_name %></td>
    <td><%= payment_method.last_name %></td>
    <td><%= payment_method.address_1 %></td>
    <td><%= payment_method.address_2 %></td>
    <td><%= payment_method.city %></td>
    <td><%= payment_method.state %></td>
    <td><%= payment_method.zip %></td>
    <td><%= payment_method.cc_last_4 %></td>
    <td><%= payment_method.cc_type %></td>
    <td><%= payment_method.cc_exp_month %></td>
    <td><%= payment_method.cc_exp_year %></td>
    <td><%= link_to 'Show', payment_method %></td>
    <td><%= link_to 'Edit', edit_payment_method_path(payment_method) %></td>
    <td><%= link_to 'Destroy', payment_method, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Payment method', new_payment_method_path %>

app/views/payment_methods/new.html.erb
<h1>New payment_method</h1>

<%= render 'form' %>

<%= link_to 'Back', payment_methods_path %>

app/views/payment_methods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cs subscription:</b>
  <%= @payment_method.cs_subscription_id %>
</p>

<p>
  <b>First name:</b>
  <%= @payment_method.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @payment_method.last_name %>
</p>

<p>
  <b>Address 1:</b>
  <%= @payment_method.address_1 %>
</p>

<p>
  <b>Address 2:</b>
  <%= @payment_method.address_2 %>
</p>

<p>
  <b>City:</b>
  <%= @payment_method.city %>
</p>

<p>
  <b>State:</b>
  <%= @payment_method.state %>
</p>

<p>
  <b>Zip:</b>
  <%= @payment_method.zip %>
</p>

<p>
  <b>Cc last 4:</b>
  <%= @payment_method.cc_last_4 %>
</p>

<p>
  <b>Cc type:</b>
  <%= @payment_method.cc_type %>
</p>

<p>
  <b>Cc exp month:</b>
  <%= @payment_method.cc_exp_month %>
</p>

<p>
  <b>Cc exp year:</b>
  <%= @payment_method.cc_exp_year %>
</p>


<%= link_to 'Edit', edit_payment_method_path(@payment_method) %> |
<%= link_to 'Back', payment_methods_path %>