config/routes.rb
Dailydeals::Application.routes.draw do

  resources :payment_methods

  resources :coupons

  resources :locations
  
  resources :businesses

  resources :sales

  resources :deals do
    collection do
      get 'current'
    end
  end
  
  devise_for :users do
    get "/users/login" => "devise/sessions#new"
    get "/users/logout" => "devise/sessions#destroy"
  end

  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
  end
  
  match "/contact",     :to => "pages#contact",                    :as => :contact
  match "/howitworks",  :to => "pages#show", :id => "howitworks",  :as => :howitworks
  match "/faq",         :to => "pages#show", :id => "faq",         :as => :faq
  match "/termsofsale", :to => "pages#show", :id => "termsofsale", :as => :termsofsale
  match "/termsofuse",  :to => "pages#show", :id => "termsofuse",  :as => :termsofuse
  match "/privacy",     :to => "pages#show", :id => "privacy",     :as => :privacy
  
  root :to => "deals#current"

end

app/models/deal.rb
class Deal < ActiveRecord::Base
  has_many :sales
  belongs_to :business
  
  def off
    (((self.value-self.price)/self.value)*100).floor
  end
  
  def activated
    true if self.activated_at
  end
  
  def savings
    self.value - self.price
  end
  
  def sold
    5
    #TODO: Implement
  end
  
  def remaining
    5
    #TODO: Implement
  end
  
  
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  # GET /deals
  # GET /deals.xml
  def index
    @deals = Deal.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @deals }
    end
  end

  # GET /deals/1
  # GET /deals/1.xml
  def show
    
    @deal = Deal.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @deal }
    end
  end

  # GET /deals/new
  # GET /deals/new.xml
  def new
    @deal = Deal.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @deal }
    end
  end

  # GET /deals/1/edit
  def edit
    @deal = Deal.find(params[:id])
  end

  # POST /deals
  # POST /deals.xml
  def create
    @deal = Deal.new(params[:deal])

    respond_to do |format|
      if @deal.save
        format.html { redirect_to(@deal, :notice => 'Deal was successfully created.') }
        format.xml  { render :xml => @deal, :status => :created, :location => @deal }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @deal.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /deals/1
  # PUT /deals/1.xml
  def update
    @deal = Deal.find(params[:id])

    respond_to do |format|
      if @deal.update_attributes(params[:deal])
        format.html { redirect_to(@deal, :notice => 'Deal was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @deal.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /deals/1
  # DELETE /deals/1.xml
  def destroy
    @deal = Deal.find(params[:id])
    @deal.destroy

    respond_to do |format|
      format.html { redirect_to(deals_url) }
      format.xml  { head :ok }
    end
  end
  
  def current
    @deal = Deal.where(["day <= :today AND expires >= :today", {:today => Time.now.to_date}]).first

    respond_to do |format|
      format.html { render 'show' }# show.html.erb
      format.xml  { render :xml => @deal }
      format.rss  { render :rss => @deal }
    end
  end
  
  
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/views/deals/_company_info.erb
<%= #TODO: Deals Company Info partial %>
<div class="mod-ext grid-580 scp_bg_color5 comp_info">
  <div class="the_deal_details_wrapper">
    <div class="the_deal_details mod-ext grid-350 f-left">
      <div class="title txt5 scp_color4">Detail:</div>
      <div>
        <h2 class="scp_color2"><?php echo $deal['Business']['name']; ?></h2>
        <div class="deal_description">
          <?php echo $markdown->parse($deal['Deal']['description']) ; ?>
          <?php echo $markdown->parse($deal['Deal']['details']) ; ?>
          <?php echo $markdown->parse($deal['Deal']['disclaimer']) ; ?>
        </div>
      </div>
    </div><!--details ends here -->

    <div class="company_info mod-ext grid-180 f-right">
      <div class="txt5 scp_color4">Company Info:</div>
      <h3 class="scp_color2">
        <?php echo $deal['Business']['name']; ?>
      </h3>
      <div class="scp_color6 txt8">
        <span class="txt9">
          <a href="<?php echo $deal['Business']['url']; ?>" rel="external">
            website
          </a>
        </span>
        <br />
        
      <?php if (isset($deal['Business']['Location'])) { ?>
        <ul class="mod">
        <?php foreach ($deal['Business']['Location'] as $loc) { ?>
          <li style="margin:15px 0 0;">
            <?php echo $loc['title']; ?><br />
            <?php echo $loc['address1']; ?><br />
            <?php if (isset($loc['address2'])) { ?>
            <?php echo $loc['address2']; ?>
            <?php } ?>
            <?php echo $loc['city']; ?>,
            <?php echo $loc['state']; ?>
            <?php echo $loc['zip']; ?><br />
            <?php echo $loc['phone']; ?><br />
          </li>
        <?php } ?>
        <div class="clear"></clear>
        </ul>
      <?php } ?>    
        <a href="http://wimgo.com/business/<?php echo $deal['Business']['venue_id']; ?>" rel="external">
          <?php echo $html->image('http://wimgodeals.wimgo.com/img/view_on_wimgo.png', array('alt' => 'View on Wimgo'))?>
        </a>
      </div>
      <div class="mod sep_beige2"></div>
      <div class="mod"><!-- charity piece -->
        <div class="we_believe">
          <div class="mod-ext scp_bg_color9 rounded txt1-small color0">
            WE BELIEVE in GIVING
          </div>
        </div>
        <div class="mod-ext rounded_bottom bg-color0" style="margin:-12px 0 0;">
          <div class="mod-ext txt8">
            <?php echo $deal['Business']['charity_text']; ?>
          </div>
          <div class="center">
            <?php echo '<img src="http://s3.amazonaws.com/wimgo-deals/' . $deal['Business']['charity_photo'] . '" alt="" style="display:inline;" />'; ?>
          </div>
        </div>
      </div><!-- charity piece ends here -->  
    </div><!-- company info ends here -->
    <div class="clear"></div>
  </div>
</div><!-- deal details end here -->
<br />

app/views/deals/_form.html.erb
<%= form_for(@deal) do |f| %>
  <% if @deal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deal.errors.count, "error") %> prohibited this deal from being saved:</h2>

      <ul>
      <% @deal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :intro %><br />
    <%= f.text_field :intro %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :day %><br />
    <%= f.date_select :day %>
  </div>
  <div class="field">
    <%= f.label :photo %><br />
    <%= f.text_field :photo %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :value %><br />
    <%= f.text_field :value %>
  </div>
  <div class="field">
    <%= f.label :min %><br />
    <%= f.text_field :min %>
  </div>
  <div class="field">
    <%= f.label :max %><br />
    <%= f.text_field :max %>
  </div>
  <div class="field">
    <%= f.label :disclaimer %><br />
    <%= f.text_area :disclaimer %>
  </div>
  <div class="field">
    <%= f.label :details %><br />
    <%= f.text_area :details %>
  </div>
  <div class="field">
    <%= f.label :activated_at %><br />
    <%= f.datetime_select :activated_at %>
  </div>
  <div class="field">
    <%= f.label :expires %><br />
    <%= f.date_select :expires %>
  </div>
  <div class="field">
    <%= f.label :coupon_expires %><br />
    <%= f.datetime_select :coupon_expires %>
  </div>
  <div class="field">
    <%= f.label :hide %><br />
    <%= f.check_box :hide %>
  </div>
  <div class="field">
    <%= f.label :coupon_instructions %><br />
    <%= f.text_area :coupon_instructions %>
  </div>
  <div class="field">
    <%= f.label :coupon_limit %><br />
    <%= f.text_field :coupon_limit %>
  </div>
  <div class="field">
    <%= f.label :auths_processed %><br />
    <%= f.check_box :auths_processed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/deals/_tell_a_friend.erb
<div class="tell_friends f-right">
  <div class="txt7 scp_color2 center">
    <div class="txt18" style="background:url(http://wimgodeals.wimgo.com/img/char_heart.jpg) right top no-repeat;width:130px;margin:0 auto;text-indent:-15px;">Help our Charities!</div>
    Tell your friends.
  </div>
  <ul class="mod center">
    <li>
      <a href="http://www.facebook.com/sharer.php?u=<?php echo urlencode($html->url(array('controller' => 'deals', 'action' => 'index', 'today' => Inflector::slug($deal['Deal']['title'])), true)); ?>&t=<?php
        echo urlencode($deal['Deal']['title']); ?>" rel="external" title="Tell your friends on Facebook">
        <?php echo $html->image('http://wimgodeals.wimgo.com/img/facebook_35x35.png', array('alt' => 'Tell your friends on Facebook'))?>
      </a>
    </li>
    <li>
      <a href="http://twitter.com/home?status=<?php echo urlencode('Amazing Deal: ' . $deal['Deal']['title'] . ' - http://wim.gs/cxS66Z'); ?>" rel="external" title="Tell your friends on Twitter">
        <?php echo $html->image('http://wimgodeals.wimgo.com/img/twitter_35x35.png', array('alt' => 'Tell your friends on Twitter'))?>
      </a>
    </li>
    <li>
      <a href="/deals/email" title="Tell your friends by email">
        <?php echo $html->image('http://wimgodeals.wimgo.com/img/email_35x35.png', array('alt' => 'Tell your friends by email'))?>
      </a>
    </li>
    <div class="clear"></div>
  </ul>
  <div class="clear"></div>
</div><!-- tell friends ends here -->

app/views/deals/edit.html.erb
<h1>Editing deal</h1>

<%= render 'form' %>

<%= link_to 'Show', @deal %> |
<%= link_to 'Back', deals_path %>

app/views/deals/index.html.erb
<h1>Listing deals</h1>

<table>
  <tr>
    <th>Intro</th>
    <th>Title</th>
    <th>Description</th>
    <th>Day</th>
    <th>Photo</th>
    <th>Price</th>
    <th>Value</th>
    <th>Min</th>
    <th>Max</th>
    <th>Disclaimer</th>
    <th>Details</th>
    <th>Activated at</th>
    <th>Expires</th>
    <th>Coupon expires</th>
    <th>Hide</th>
    <th>Coupon instructions</th>
    <th>Coupon limit</th>
    <th>Auths processed</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @deals.each do |deal| %>
  <tr>
    <td><%= deal.intro %></td>
    <td><%= deal.title %></td>
    <td><%= deal.description %></td>
    <td><%= deal.day %></td>
    <td><%= deal.photo %></td>
    <td><%= deal.price %></td>
    <td><%= deal.value %></td>
    <td><%= deal.min %></td>
    <td><%= deal.max %></td>
    <td><%= deal.disclaimer %></td>
    <td><%= deal.details %></td>
    <td><%= deal.activated_at %></td>
    <td><%= deal.expires %></td>
    <td><%= deal.coupon_expires %></td>
    <td><%= deal.hide %></td>
    <td><%= deal.coupon_instructions %></td>
    <td><%= deal.coupon_limit %></td>
    <td><%= deal.auths_processed %></td>
    <td><%= link_to 'Show', deal %></td>
    <td><%= link_to 'Edit', edit_deal_path(deal) %></td>
    <td><%= link_to 'Destroy', deal, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Deal', new_deal_path %>

app/views/deals/new.html.erb
<h1>New deal</h1>

<%= render 'form' %>

<%= link_to 'Back', deals_path %>

app/views/deals/show.html.erb
<script>
jQuery('.nav li:first').addClass('current');
</script>
<div class="mod-ext grid-580 bg-color0">
  <div class="mod-ext todays_scp scp_color2 txt2">
    <span class="scp_color1">Today's deal:</span> <%= @deal.title %>
  </div>
  <div class="mod-ext the_deal">
    <div class="the_deal_snap">
      <img src="http://s3.amazonaws.com/wimgo-deals/<%= @deal.photo %>" alt="<%= @deal.title %>" />
    </div>
    <div class="the_deal_info">
      <div class="mod center scp_color1 txt3">
        $<%= @deal.price %>
      </div>
      <!-- <a href="https://secure.wimgo.com/deals/?deal_id=<?php echo $deal['Deal']['id']; ?>&unique_id=<?php echo $session->read('Auth.User.unique_id'); ?>"> -->
        <!-- <?php echo $html->image('http://wimgodeals.wimgo.com/img/buy_now.png', array('alt' => 'Buy'))?> -->
        <!-- </a> -->

      <a id="buyNow" href="#"><img src="/images/deals/buy_now.png" alt="Buy"></a>
      <br />
      <div class="center">
        <ul class="value_info">
          <li>
            <%= @deal.off %>%<span>off</span>
          </li>

          <li>
            $<%= @deal.value %><span>value</span>
          </li>
          <li>
            $<%= @deal.savings %><span>savings</span>
          </li>
          <div class="clear"></div>
        </ul>
      </div>
      <div class="mod-ext center txt4 scp_color3"><span class="txt5">Hurry!</span> Time's a tickin'.</div>
      <div class="the_time">
        <div id="countdown" class="timer scp_bg_color4 rounded center txt5 color0"></div>
        <span class="txt6 center w-60">hours</span>
        <span class="txt6 center w-60">minutes</span>
        <span class="txt6 center w-60">seconds</span>
      </div>
    </div><!-- deal info ends here -->
    <div class="clear"></div>
    <div class="mod some_info">
      <br />
      <% if @deal.activated %>
        <% if @deal.max && @deal.sold >= (0.75 * @deal.max) %>
      <div id="progress_bar_wrapper" class="f-left">
        <div class="f-left txt8 status">Status: <span class="scp_color1 txt-trans-up">ACTIVE!</span></div>
        <div class="f-right sold scp_color2 txt4"><span class="txt2"><%= @deal.sold %></span> have been sold.</div>
        <div class="clear"></div>
        <div id="progress_bar">
          <div class="indicator step_2">bar</div>
        </div>
        <div class=" mod f-right scp_color2 txt8">
          Act Now - Only <span class="scp_color11"><%= (@deal.max - @deal.sold) %></span> available.
        </div>
      </div>
        <% else %>
      <div class="deal_on">
        <div class="scp_color2 purchases lh-55">
          <%= @deal.sold %> purchased.
        </div>
      </div>
        <% end %>
      <% else %>
      <div id="progress_bar_wrapper" class="f-left">
        <div class="f-left txt8 status">Status: <span class="scp_color11 txt-trans-up">Not yet active!</span></div>
        <div class="f-right sold scp_color2 txt4">
          <span class="txt2"><%= @deal.sold %></span> have been sold.
        </div>
        <div class="clear"></div>
        <div id="progress_bar">
          <div class="indicator step_1">bar</div>
        <% if @deal.min == 10 && @deal.sold <= 10 %>
          <div class="indicator step_2" style="width:<%= @deal.sold*5 %>px;position:absolute;top:0;left:0;">
            bar
          </div>
        <% elsif @deal.min == 5 && @deal.sold <= 5 %>
          <div class="indicator step_2" style="width:<%= @deal.sold*10 %>px;position:absolute;top:0;left:0;">
            bar
          </div>
        <% end %>
        </div>
        <div class="f-left activation scp_color13">
          <strong><%= @deal.remaining %></strong> to activate.
        </div>
        <div class="f-right"></div>
        <div class="clear"></div>
      </div>
      <% end %>


      <%#= render "tell_a_friend" %>

      <div class="clear"></div>
    </div><!-- deal's on ends here -->
  </div><!-- current deal ends here -->
</div><!-- inner container ends here -->

<%#= render "company_info" %>

<%= link_to 'Edit', edit_deal_path(@deal) %> <!-- | -->
<%= link_to 'Back', deals_path %>