config/routes.rb
Dailydeals::Application.routes.draw do

  resources :payment_methods

  resources :coupons

  resources :locations
  
  resources :businesses

  resources :sales

  resources :deals do
    collection do
      get 'current'
    end
  end
  
  devise_for :users do
    get "/users/login" => "devise/sessions#new"
    get "/users/logout" => "devise/sessions#destroy"
  end

  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
  end
  
  match "/contact",     :to => "pages#contact",                    :as => :contact
  match "/howitworks",  :to => "pages#show", :id => "howitworks",  :as => :howitworks
  match "/faq",         :to => "pages#show", :id => "faq",         :as => :faq
  match "/termsofsale", :to => "pages#show", :id => "termsofsale", :as => :termsofsale
  match "/termsofuse",  :to => "pages#show", :id => "termsofuse",  :as => :termsofuse
  match "/privacy",     :to => "pages#show", :id => "privacy",     :as => :privacy
  
  root :to => "deals#current"

end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :users
  belongs_to :deals
  has_many :coupons
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  # GET /sales
  # GET /sales.xml
  def index
    @sales = Sale.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @sales }
    end
  end

  # GET /sales/1
  # GET /sales/1.xml
  def show
    @sale = Sale.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @sale }
    end
  end

  # GET /sales/new
  # GET /sales/new.xml
  def new
    @sale = Sale.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @sale }
    end
  end

  # GET /sales/1/edit
  def edit
    @sale = Sale.find(params[:id])
  end

  # POST /sales
  # POST /sales.xml
  def create
    @sale = Sale.new(params[:sale])

    respond_to do |format|
      if @sale.save
        format.html { redirect_to(@sale, :notice => 'Sale was successfully created.') }
        format.xml  { render :xml => @sale, :status => :created, :location => @sale }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @sale.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /sales/1
  # PUT /sales/1.xml
  def update
    @sale = Sale.find(params[:id])

    respond_to do |format|
      if @sale.update_attributes(params[:sale])
        format.html { redirect_to(@sale, :notice => 'Sale was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @sale.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.xml
  def destroy
    @sale = Sale.find(params[:id])
    @sale.destroy

    respond_to do |format|
      format.html { redirect_to(sales_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<%= form_for(@sale) do |f| %>
  <% if @sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% @sale.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.text_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :auth_request_token %><br />
    <%= f.text_field :auth_request_token %>
  </div>
  <div class="field">
    <%= f.label :auth_request_id %><br />
    <%= f.text_field :auth_request_id %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :address_1 %><br />
    <%= f.text_field :address_1 %>
  </div>
  <div class="field">
    <%= f.label :address_2 %><br />
    <%= f.text_field :address_2 %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br />
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :card_expiration %><br />
    <%= f.date_select :card_expiration %>
  </div>
  <div class="field">
    <%= f.label :card_type %><br />
    <%= f.text_field :card_type %>
  </div>
  <div class="field">
    <%= f.label :gift_first_name %><br />
    <%= f.text_field :gift_first_name %>
  </div>
  <div class="field">
    <%= f.label :gift_last_name %><br />
    <%= f.text_field :gift_last_name %>
  </div>
  <div class="field">
    <%= f.label :gift_email %><br />
    <%= f.text_field :gift_email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sales/edit.html.erb
<h1>Editing sale</h1>

<%= render 'form' %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<h1>Listing sales</h1>

<table>
  <tr>
    <th>Email</th>
    <th>Quantity</th>
    <th>Auth request token</th>
    <th>Auth request</th>
    <th>First name</th>
    <th>Last name</th>
    <th>Address 1</th>
    <th>Address 2</th>
    <th>City</th>
    <th>State</th>
    <th>Zip</th>
    <th>Phone</th>
    <th>Card expiration</th>
    <th>Card type</th>
    <th>Gift first name</th>
    <th>Gift last name</th>
    <th>Gift email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sales.each do |sale| %>
  <tr>
    <td><%= sale.email %></td>
    <td><%= sale.quantity %></td>
    <td><%= sale.auth_request_token %></td>
    <td><%= sale.auth_request_id %></td>
    <td><%= sale.first_name %></td>
    <td><%= sale.last_name %></td>
    <td><%= sale.address_1 %></td>
    <td><%= sale.address_2 %></td>
    <td><%= sale.city %></td>
    <td><%= sale.state %></td>
    <td><%= sale.zip %></td>
    <td><%= sale.phone %></td>
    <td><%= sale.card_expiration %></td>
    <td><%= sale.card_type %></td>
    <td><%= sale.gift_first_name %></td>
    <td><%= sale.gift_last_name %></td>
    <td><%= sale.gift_email %></td>
    <td><%= link_to 'Show', sale %></td>
    <td><%= link_to 'Edit', edit_sale_path(sale) %></td>
    <td><%= link_to 'Destroy', sale, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sale', new_sale_path %>

app/views/sales/new.html.erb
<h1>New sale</h1>

<%= render 'form' %>

<%= link_to 'Back', sales_path %>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @sale.email %>
</p>

<p>
  <b>Quantity:</b>
  <%= @sale.quantity %>
</p>

<p>
  <b>Auth request token:</b>
  <%= @sale.auth_request_token %>
</p>

<p>
  <b>Auth request:</b>
  <%= @sale.auth_request_id %>
</p>

<p>
  <b>First name:</b>
  <%= @sale.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @sale.last_name %>
</p>

<p>
  <b>Address 1:</b>
  <%= @sale.address_1 %>
</p>

<p>
  <b>Address 2:</b>
  <%= @sale.address_2 %>
</p>

<p>
  <b>City:</b>
  <%= @sale.city %>
</p>

<p>
  <b>State:</b>
  <%= @sale.state %>
</p>

<p>
  <b>Zip:</b>
  <%= @sale.zip %>
</p>

<p>
  <b>Phone:</b>
  <%= @sale.phone %>
</p>

<p>
  <b>Card expiration:</b>
  <%= @sale.card_expiration %>
</p>

<p>
  <b>Card type:</b>
  <%= @sale.card_type %>
</p>

<p>
  <b>Gift first name:</b>
  <%= @sale.gift_first_name %>
</p>

<p>
  <b>Gift last name:</b>
  <%= @sale.gift_last_name %>
</p>

<p>
  <b>Gift email:</b>
  <%= @sale.gift_email %>
</p>


<%= link_to 'Edit', edit_sale_path(@sale) %> |
<%= link_to 'Back', sales_path %>